#!/usr/bin/env python3
"""Check source, archive, and installed-copy release consistency."""

import argparse
import hashlib
import json
import re
import sys
import zipfile
from pathlib import Path


SECRET_ASSIGNMENT = re.compile(
    r"(?i)(api[_-]?key|access[_-]?token|password|secret)\s*[:=]\s*[\"'][A-Za-z0-9_\-]{16,}[\"']"
)
PERSONAL_PATH = re.compile(
    r"(?i)([A-Z]:\\" + "Users" + r"\\[^\\\s]+|/" + "Users" + r"/[^/\s]+|/home/[^/\s]+)"
)


def _read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _version_from_pyproject(text):
    match = re.search(r"(?m)^version\s*=\s*[\"']([^\"']+)[\"']", text)
    return match.group(1) if match else None


def check_release(root, archive=None, installed=None):
    root = Path(root).resolve()
    findings = []
    try:
        manifest = _read_json(root / "release" / "manifest.json")
        version = (root / "VERSION").read_text(encoding="utf-8").strip()
    except (OSError, json.JSONDecodeError) as exc:
        return {"passed": False, "findings": [{"code": "RELEASE_INPUT", "message": str(exc)}]}
    skill_root = root / manifest["skill_directory"]

    versions = {
        "VERSION": version,
        "manifest": manifest.get("skill_version"),
        "pyproject": _version_from_pyproject((root / "pyproject.toml").read_text(encoding="utf-8")),
        "quality_policy": _read_json(skill_root / "schemas" / "quality-policy.json").get("skill_version"),
    }
    if len(set(versions.values())) != 1:
        findings.append({"code": "RELEASE_VERSION_MISMATCH", "message": "Version declarations differ", "details": versions})

    skill_text = (skill_root / "SKILL.md").read_text(encoding="utf-8")
    frontmatter = re.search(r"\A---\s*\n(.*?)\n---", skill_text, re.DOTALL)
    name_match = re.search(r"(?m)^name:\s*([^\s]+)\s*$", frontmatter.group(1) if frontmatter else "")
    if not name_match or name_match.group(1) != manifest.get("skill_name") or skill_root.name != manifest.get("skill_name"):
        findings.append({"code": "RELEASE_SKILL_NAME_MISMATCH", "message": "Skill folder, frontmatter, and manifest names must match"})
    if "TODO" in skill_text:
        findings.append({"code": "RELEASE_TODO", "message": "SKILL.md contains TODO text"})

    for relative in manifest.get("required_runtime_files") or []:
        if not (skill_root / relative).is_file():
            findings.append({"code": "RELEASE_REQUIRED_FILE_MISSING", "message": "Missing runtime file: %s" % relative})
    for relative in manifest.get("required_repository_paths") or []:
        if not (root / relative).exists():
            findings.append({"code": "RELEASE_REQUIRED_FILE_MISSING", "message": "Missing repository path: %s" % relative})

    source_files = []
    for path in skill_root.rglob("*"):
        if path.is_dir():
            if path.name == "__pycache__":
                findings.append({"code": "RELEASE_CACHE_ARTIFACT", "message": "Generated cache directory is present: %s" % path})
            continue
        if path.suffix == ".pyc":
            findings.append({"code": "RELEASE_CACHE_ARTIFACT", "message": "Generated bytecode is present: %s" % path})
            continue
        relative = path.relative_to(skill_root).as_posix()
        source_files.append(relative)
        if path.suffix == ".json":
            try:
                _read_json(path)
            except (OSError, json.JSONDecodeError) as exc:
                findings.append({"code": "RELEASE_INVALID_JSON", "message": "%s: %s" % (relative, exc)})
        if path.suffix in (".py", ".md", ".yaml", ".yml", ".json"):
            try:
                text = path.read_text(encoding="utf-8")
                if SECRET_ASSIGNMENT.search(text):
                    findings.append({"code": "RELEASE_POSSIBLE_SECRET", "message": "Possible embedded credential in %s" % relative})
                if PERSONAL_PATH.search(text):
                    findings.append({"code": "RELEASE_PERSONAL_PATH", "message": "Possible personal absolute path in %s" % relative})
                if path.suffix == ".py":
                    compile(text, str(path), "exec")
            except (UnicodeDecodeError, SyntaxError) as exc:
                findings.append({"code": "RELEASE_SOURCE_INVALID", "message": "%s: %s" % (relative, exc)})

    if archive:
        archive_path = Path(archive).resolve()
        try:
            with zipfile.ZipFile(str(archive_path), "r") as handle:
                entries = {name for name in handle.namelist() if not name.endswith("/")}
                expected = {"%s/%s" % (manifest["skill_name"], relative) for relative in source_files}
                if entries != expected:
                    findings.append({"code": "RELEASE_ARCHIVE_CONTENT_MISMATCH", "message": "Archive entries do not exactly match runtime source", "details": {"missing": sorted(expected - entries), "extra": sorted(entries - expected)}})
                else:
                    for relative in source_files:
                        entry = "%s/%s" % (manifest["skill_name"], relative)
                        if _sha256(skill_root / relative) != hashlib.sha256(handle.read(entry)).hexdigest():
                            findings.append({"code": "RELEASE_ARCHIVE_HASH_MISMATCH", "message": "Archive differs for %s" % relative})
        except (OSError, zipfile.BadZipFile) as exc:
            findings.append({"code": "RELEASE_ARCHIVE_INVALID", "message": str(exc)})

    if installed:
        installed_root = Path(installed).resolve()
        for relative in source_files:
            target = installed_root / relative
            if not target.is_file():
                findings.append({"code": "RELEASE_INSTALL_FILE_MISSING", "message": "Installed copy lacks %s" % relative})
            elif _sha256(skill_root / relative) != _sha256(target):
                findings.append({"code": "RELEASE_INSTALL_HASH_MISMATCH", "message": "Installed copy differs for %s" % relative})

    return {"report_schema_version": "1.0", "skill_version": version, "passed": not findings, "runtime_files": len(source_files), "findings": findings}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(Path(__file__).resolve().parents[1]))
    parser.add_argument("--archive")
    parser.add_argument("--installed")
    args = parser.parse_args(argv)
    report = check_release(args.root, args.archive, args.installed)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
